DEFINE SCHEMA

    CREATE ROLE member;
    CREATE ROLE viewer;

    RECORD TYPE AllOtherTypes (
        "___createTime" TIMESTAMP,
        "___createdBy"  REFERENCE,
        "___etag"       STRING,
        "___modTime"    TIMESTAMP,
        "___modifiedBy" REFERENCE,
        "___recordID"   REFERENCE QUERYABLE,
        readableby      STRING,
        GRANT WRITE TO "_creator",
        GRANT CREATE TO "_icloud",
        GRANT READ TO "_world",
        GRANT READ, WRITE TO member,
        GRANT READ TO viewer
    );

    RECORD TYPE ChangeOrder (
        "___createTime"  TIMESTAMP,
        "___createdBy"   REFERENCE,
        "___etag"        STRING,
        "___modTime"     TIMESTAMP,
        "___modifiedBy"  REFERENCE,
        "___recordID"    REFERENCE QUERYABLE,
        amount           DOUBLE QUERYABLE SORTABLE,
        approvedBy       STRING QUERYABLE,
        attachments      LIST<STRING>,
        changeNumber     INT64 QUERYABLE SORTABLE,
        clientApproval   INT64,
        createdBy        STRING QUERYABLE,
        dateApproved     TIMESTAMP QUERYABLE SORTABLE,
        dateCreated      TIMESTAMP QUERYABLE SORTABLE,
        description      STRING,
        environment      STRING QUERYABLE,
        impactToBudget   DOUBLE,
        impactToSchedule STRING,
        organizationID   STRING QUERYABLE,
        projectID        STRING QUERYABLE,
        reason           STRING,
        status           STRING QUERYABLE,
        GRANT READ, WRITE TO member,
        GRANT READ TO viewer
    );

    RECORD TYPE CommunicationLog (
        "___createTime"   TIMESTAMP,
        "___createdBy"    REFERENCE,
        "___etag"         STRING,
        "___modTime"      TIMESTAMP,
        "___modifiedBy"   REFERENCE,
        "___recordID"     REFERENCE QUERYABLE,
        attachments       LIST<STRING>,
        communicationType STRING QUERYABLE,
        content           STRING,
        createdBy         STRING QUERYABLE,
        dateCreated       TIMESTAMP QUERYABLE SORTABLE,
        environment       STRING QUERYABLE,
        followUpDate      TIMESTAMP,
        followUpRequired  INT64,
        organizationID    STRING QUERYABLE,
        priority          STRING QUERYABLE,
        projectID         STRING QUERYABLE,
        recipientEmails   LIST<STRING>,
        subject           STRING QUERYABLE SEARCHABLE,
        GRANT READ, WRITE TO member,
        GRANT READ TO viewer
    );

    RECORD TYPE Employee (
        "___createTime" TIMESTAMP,
        "___createdBy"  REFERENCE,
        "___etag"       STRING,
        "___modTime"    TIMESTAMP,
        "___modifiedBy" REFERENCE,
        "___recordID"   REFERENCE QUERYABLE,
        createdAt       TIMESTAMP,
        email           STRING QUERYABLE SEARCHABLE SORTABLE,
        environment     STRING QUERYABLE,
        hourlyRate      DOUBLE,
        id              STRING QUERYABLE SEARCHABLE SORTABLE,
        isActive        INT64,
        isArchived      INT64 QUERYABLE SORTABLE,
        jobTitle        STRING,
        name            STRING QUERYABLE SORTABLE,
        organizationID  STRING QUERYABLE,
        rates           BYTES QUERYABLE SORTABLE,
        GRANT WRITE TO "_creator",
        GRANT CREATE TO "_icloud",
        GRANT READ TO "_world"
    );

    RECORD TYPE Organization (
        "___createTime"  TIMESTAMP,
        "___createdBy"   REFERENCE,
        "___etag"        STRING,
        "___modTime"     TIMESTAMP,
        "___modifiedBy"  REFERENCE,
        "___recordID"    REFERENCE QUERYABLE,
        adminUserID      STRING QUERYABLE,
        createdAt        TIMESTAMP,
        dateCreated      TIMESTAMP SORTABLE,
        environment      STRING QUERYABLE,
        id               STRING QUERYABLE SEARCHABLE SORTABLE,
        inviteToken      STRING QUERYABLE SEARCHABLE SORTABLE,
        isActive         STRING QUERYABLE,
        isActiveV2       INT64,
        maxMembers       STRING,
        maxMembersV2     INT64,
        memberRoles      STRING,
        members          LIST<STRING> QUERYABLE SEARCHABLE SORTABLE,
        name             STRING QUERYABLE SEARCHABLE SORTABLE,
        orgID            STRING QUERYABLE,
        orgName          STRING,
        organizationID   STRING,
        pendingInvites   LIST<STRING>,
        settings         STRING,
        subscriptionType STRING,
        GRANT READ, WRITE TO "_creator",
        GRANT READ, CREATE TO "_icloud",
        GRANT READ, WRITE TO member
    );

    RECORD TYPE OrganizationInvite (
        "___createTime" TIMESTAMP,
        "___createdBy"  REFERENCE,
        "___etag"       STRING,
        "___modTime"    TIMESTAMP,
        "___modifiedBy" REFERENCE,
        "___recordID"   REFERENCE QUERYABLE,
        createdAt       TIMESTAMP QUERYABLE,
        environment     STRING QUERYABLE,
        expiresAt       TIMESTAMP QUERYABLE,
        inviteToken     STRING QUERYABLE,
        inviteeEmail    STRING QUERYABLE,
        inviterUserID   STRING QUERYABLE,
        organizationID  STRING QUERYABLE,
        role            STRING QUERYABLE,
        status          STRING QUERYABLE,
        GRANT WRITE TO "_creator",
        GRANT CREATE TO "_icloud",
        GRANT READ TO "_world",
        GRANT READ, WRITE TO member
    );

    RECORD TYPE OrganizationMember (
        "___createTime" TIMESTAMP,
        "___createdBy"  REFERENCE,
        "___etag"       STRING,
        "___modTime"    TIMESTAMP,
        "___modifiedBy" REFERENCE,
        "___recordID"   REFERENCE QUERYABLE,
        emai            STRING,
        email           STRING QUERYABLE,
        environment     STRING QUERYABLE,
        invitedBy       STRING QUERYABLE,
        joinedAt        TIMESTAMP,
        organizationID  STRING QUERYABLE,
        role            STRING QUERYABLE,
        status          STRING QUERYABLE,
        userID          STRING QUERYABLE,
        GRANT WRITE TO "_creator",
        GRANT CREATE TO "_icloud",
        GRANT READ TO "_world"
    );

    RECORD TYPE OrganizationRoot (
        "___createTime" TIMESTAMP,
        "___createdBy"  REFERENCE,
        "___etag"       STRING,
        "___modTime"    TIMESTAMP,
        "___modifiedBy" REFERENCE,
        "___recordID"   REFERENCE QUERYABLE,
        createdAt       TIMESTAMP SORTABLE,
        description     STRING,
        environment     STRING QUERYABLE,
        name            STRING QUERYABLE SEARCHABLE SORTABLE,
        organizationID  STRING QUERYABLE SORTABLE,
        zoneVersion     INT64,
        GRANT READ, WRITE TO "_creator",
        GRANT CREATE TO "_icloud",
        GRANT READ TO "_world",
        GRANT READ, WRITE TO member,
        GRANT READ TO viewer
    );

    RECORD TYPE OrganizationSpendingSummary (
        "___createTime"        TIMESTAMP,
        "___createdBy"         REFERENCE,
        "___etag"              STRING,
        "___modTime"           TIMESTAMP,
        "___modifiedBy"        REFERENCE,
        "___recordID"          REFERENCE,
        environment            STRING QUERYABLE,
        generatedBy            STRING QUERYABLE,
        lastUpdated            TIMESTAMP SORTABLE,
        organizationID         STRING QUERYABLE,
        paymentMethodBreakdown BYTES,
        projectBreakdown       BYTES,
        summaryDate            TIMESTAMP QUERYABLE SORTABLE,
        totalSpent             DOUBLE SORTABLE,
        vendorBreakdown        BYTES,
        GRANT READ, WRITE TO member,
        GRANT READ TO viewer
    );

    RECORD TYPE PaymentMethod (
        "___createTime" TIMESTAMP,
        "___createdBy"  REFERENCE,
        "___etag"       STRING,
        "___modTime"    TIMESTAMP,
        "___modifiedBy" REFERENCE,
        "___recordID"   REFERENCE,
        accountNumber   STRING,
        cardBrand       STRING,
        createdBy       STRING QUERYABLE,
        dateAdded       TIMESTAMP SORTABLE,
        environment     STRING QUERYABLE,
        id              STRING QUERYABLE SORTABLE,
        isActive        INT64 QUERYABLE,
        lastFourDigits  STRING,
        lastUpdated     TIMESTAMP SORTABLE,
        lastUsed        TIMESTAMP SORTABLE,
        name            STRING QUERYABLE SEARCHABLE SORTABLE,
        nickname        STRING,
        organizationID  STRING QUERYABLE,
        projectsUsed    LIST<STRING>,
        totalSpent      DOUBLE SORTABLE,
        type            STRING QUERYABLE SORTABLE,
        GRANT READ, WRITE TO member,
        GRANT READ TO viewer
    );

    RECORD TYPE PendingInvitation (
        "___createTime" TIMESTAMP,
        "___createdBy"  REFERENCE,
        "___etag"       STRING,
        "___modTime"    TIMESTAMP,
        "___modifiedBy" REFERENCE,
        "___recordID"   REFERENCE QUERYABLE,
        createdAt       TIMESTAMP,
        environment     STRING QUERYABLE,
        expiresAt       TIMESTAMP,
        inviteToken     STRING,
        invitedBy       STRING,
        invitedEmail    STRING,
        organizationID  STRING,
        status          STRING,
        GRANT WRITE TO "_creator",
        GRANT CREATE TO "_icloud",
        GRANT READ TO "_world"
    );

    RECORD TYPE ProgressLog (
        Creatableby     STRING,
        Readableby      STRING,
        WriteAccess     STRING,
        "___createTime" TIMESTAMP,
        "___createdBy"  REFERENCE,
        "___etag"       STRING,
        "___modTime"    TIMESTAMP,
        "___modifiedBy" REFERENCE,
        "___recordID"   REFERENCE QUERYABLE,
        category        STRING QUERYABLE,
        createdBy       STRING QUERYABLE,
        date            STRING QUERYABLE,
        dateV2          TIMESTAMP,
        description     STRING,
        employeeIDs     LIST<STRING> QUERYABLE,
        environment     STRING QUERYABLE,
        lastSyncedAt    TIMESTAMP,
        logDate         TIMESTAMP QUERYABLE,
        notes           STRING,
        organizationID  STRING QUERYABLE,
        photoIDs        LIST<STRING>,
        projectID       STRING QUERYABLE,
        sharedWithTeam  INT64 QUERYABLE,
        taskID          STRING,
        teamMemberIDs   LIST<STRING> QUERYABLE,
        workDescription STRING,
        GRANT WRITE TO "_creator",
        GRANT CREATE TO "_icloud",
        GRANT READ TO "_world",
        GRANT READ, WRITE TO member
    );

    RECORD TYPE ProgressPhoto (
        "___createTime" TIMESTAMP,
        "___createdBy"  REFERENCE,
        "___etag"       STRING,
        "___modTime"    TIMESTAMP,
        "___modifiedBy" REFERENCE,
        "___recordID"   REFERENCE QUERYABLE,
        environment     STRING QUERYABLE,
        organizationID  STRING QUERYABLE,
        photo           ASSET,
        photoOrder      INT64,
        progressLogID   STRING QUERYABLE,
        thumbnail       ASSET,
        uploadedAt      TIMESTAMP,
        uploadedBy      STRING QUERYABLE,
        GRANT WRITE TO "_creator",
        GRANT CREATE TO "_icloud",
        GRANT READ TO "_world",
        GRANT READ, WRITE TO member,
        GRANT READ TO viewer
    );

    RECORD TYPE Project (
        "___createTime"        TIMESTAMP,
        "___createdBy"         REFERENCE,
        "___etag"              STRING,
        "___modTime"           TIMESTAMP,
        "___modifiedBy"        REFERENCE,
        "___recordID"          REFERENCE QUERYABLE,
        assignedEmployeeEmails LIST<STRING> QUERYABLE SEARCHABLE,
        budget                 DOUBLE,
        city                   STRING QUERYABLE SEARCHABLE SORTABLE,
        client                 STRING QUERYABLE SEARCHABLE SORTABLE,
        clientName             STRING QUERYABLE,
        contingency            DOUBLE QUERYABLE SORTABLE,
        createdBy              STRING QUERYABLE,
        createdTimestamp       TIMESTAMP,
        details                STRING,
        endDate                TIMESTAMP,
        environment            STRING QUERYABLE,
        fullProjectData        BYTES,
        generalConditions      DOUBLE QUERYABLE SORTABLE,
        id                     STRING QUERYABLE SEARCHABLE SORTABLE,
        isShared               INT64 QUERYABLE SORTABLE,
        laborCost              DOUBLE QUERYABLE SORTABLE,
        lastModified           TIMESTAMP QUERYABLE SORTABLE,
        lastModifiedBy         STRING QUERYABLE SEARCHABLE SORTABLE,
        lastSyncedAt           TIMESTAMP,
        location               LOCATION,
        materialCost           DOUBLE QUERYABLE SORTABLE,
        name                   STRING QUERYABLE,
        notes                  STRING QUERYABLE SEARCHABLE SORTABLE,
        orgID                  STRING QUERYABLE,
        organizationID         STRING QUERYABLE,
        phone                  STRING QUERYABLE SEARCHABLE SORTABLE,
        profit                 DOUBLE QUERYABLE SORTABLE,
        projectID              STRING,
        sharedWithTeam         INT64 QUERYABLE,
        spentContingency       DOUBLE QUERYABLE SORTABLE,
        startDate              TIMESTAMP,
        state                  STRING QUERYABLE SEARCHABLE SORTABLE,
        status                 STRING QUERYABLE,
        street                 STRING QUERYABLE SEARCHABLE SORTABLE,
        teamMembers            LIST<STRING>,
        title                  STRING,
        totalBudget            DOUBLE QUERYABLE SORTABLE,
        zip                    STRING QUERYABLE SEARCHABLE SORTABLE,
        GRANT READ, WRITE TO "_creator",
        GRANT READ, CREATE TO "_icloud",
        GRANT READ, WRITE TO member
    );

    RECORD TYPE ProjectPaymentMethodUsage (
        "___createTime" TIMESTAMP,
        "___createdBy"  REFERENCE,
        "___etag"       STRING,
        "___modTime"    TIMESTAMP,
        "___modifiedBy" REFERENCE,
        "___recordID"   REFERENCE,
        environment     STRING QUERYABLE,
        firstUsed       TIMESTAMP SORTABLE,
        id              STRING QUERYABLE,
        lastUpdated     TIMESTAMP SORTABLE,
        lastUsed        TIMESTAMP SORTABLE,
        organizationID  STRING QUERYABLE,
        paymentMethodID STRING QUERYABLE SORTABLE,
        projectID       STRING QUERYABLE SORTABLE,
        receiptCount    INT64 SORTABLE,
        totalSpent      DOUBLE SORTABLE,
        GRANT READ, WRITE TO member,
        GRANT READ TO viewer
    );

    RECORD TYPE ProjectTask (
        "___createTime"     TIMESTAMP,
        "___createdBy"      REFERENCE,
        "___etag"           STRING,
        "___modTime"        TIMESTAMP,
        "___modifiedBy"     REFERENCE,
        "___recordID"       REFERENCE QUERYABLE,
        assignedEmployeeIDs STRING,
        category            STRING QUERYABLE,
        createdAt           TIMESTAMP,
        createdBy           STRING QUERYABLE,
        description         STRING,
        dueDate             TIMESTAMP QUERYABLE,
        environment         STRING QUERYABLE,
        isCompleted         INT64 QUERYABLE,
        lastSyncedAt        TIMESTAMP,
        organizationID      STRING QUERYABLE,
        photoIDs            LIST<STRING>,
        priority            STRING QUERYABLE,
        projectID           STRING QUERYABLE,
        title               STRING QUERYABLE,
        GRANT WRITE TO "_creator",
        GRANT CREATE TO "_icloud",
        GRANT READ TO "_world",
        GRANT READ, WRITE TO member
    );

    RECORD TYPE ProjectVendorUsage (
        "___createTime" TIMESTAMP,
        "___createdBy"  REFERENCE,
        "___etag"       STRING,
        "___modTime"    TIMESTAMP,
        "___modifiedBy" REFERENCE,
        "___recordID"   REFERENCE,
        environment     STRING QUERYABLE,
        firstUsed       TIMESTAMP SORTABLE,
        id              STRING QUERYABLE,
        lastUpdated     TIMESTAMP SORTABLE,
        lastUsed        TIMESTAMP SORTABLE,
        organizationID  STRING QUERYABLE,
        projectID       STRING QUERYABLE SORTABLE,
        receiptCount    INT64 SORTABLE,
        totalSpent      DOUBLE SORTABLE,
        vendorID        STRING QUERYABLE SORTABLE,
        GRANT READ, WRITE TO member,
        GRANT READ TO viewer
    );

    RECORD TYPE RHEIRUser (
        "___createTime" TIMESTAMP,
        "___createdBy"  REFERENCE QUERYABLE,
        "___etag"       STRING,
        "___modTime"    TIMESTAMP,
        "___modifiedBy" REFERENCE,
        "___recordID"   REFERENCE QUERYABLE,
        email           STRING,
        environment     STRING QUERYABLE,
        userID          STRING QUERYABLE,
        GRANT READ, WRITE TO "_creator",
        GRANT CREATE TO "_icloud",
        GRANT READ TO "_world"
    );

    RECORD TYPE Receipt (
        Creatableby     STRING,
        Readableby      STRING,
        WriteAccess     STRING,
        "___createTime" TIMESTAMP,
        "___createdBy"  REFERENCE,
        "___etag"       STRING,
        "___modTime"    TIMESTAMP,
        "___modifiedBy" REFERENCE,
        "___recordID"   REFERENCE QUERYABLE,
        amount          DOUBLE,
        category        STRING QUERYABLE,
        environment     STRING QUERYABLE,
        isReturn        INT64,
        lastSyncedAt    TIMESTAMP,
        notes           STRING,
        organizationID  STRING QUERYABLE,
        paymentMethodID STRING QUERYABLE,
        photoIDs        LIST<STRING>,
        projectID       STRING QUERYABLE,
        receiptDate     TIMESTAMP,
        receiptImage    ASSET,
        sharedWithTeam  INT64 QUERYABLE,
        uploadedBy      STRING QUERYABLE,
        vendor          STRING,
        vendorID        STRING QUERYABLE,
        GRANT WRITE TO "_creator",
        GRANT CREATE TO "_icloud",
        GRANT READ TO "_world",
        GRANT READ, WRITE TO member
    );

    RECORD TYPE ReceiptPhoto (
        "___createTime" TIMESTAMP,
        "___createdBy"  REFERENCE,
        "___etag"       STRING,
        "___modTime"    TIMESTAMP,
        "___modifiedBy" REFERENCE,
        "___recordID"   REFERENCE QUERYABLE,
        environment     STRING QUERYABLE,
        organizationID  STRING QUERYABLE,
        photo           ASSET,
        photoOrder      INT64,
        receiptID       STRING QUERYABLE,
        thumbnail       ASSET,
        uploadedAt      TIMESTAMP,
        uploadedBy      STRING QUERYABLE,
        GRANT READ, WRITE TO member,
        GRANT READ TO viewer
    );

    RECORD TYPE Staff (
        "___createTime" TIMESTAMP,
        "___createdBy"  REFERENCE,
        "___etag"       STRING,
        "___modTime"    TIMESTAMP,
        "___modifiedBy" REFERENCE,
        "___recordID"   REFERENCE QUERYABLE,
        environment     STRING QUERYABLE,
        orgID           STRING QUERYABLE,
        role            STRING,
        userID          STRING,
        GRANT READ, WRITE TO "_creator",
        GRANT READ, CREATE TO "_icloud",
        GRANT READ, WRITE TO member
    );

    RECORD TYPE TaskPhoto (
        "___createTime" TIMESTAMP,
        "___createdBy"  REFERENCE,
        "___etag"       STRING,
        "___modTime"    TIMESTAMP,
        "___modifiedBy" REFERENCE,
        "___recordID"   REFERENCE QUERYABLE,
        environment     STRING QUERYABLE,
        organizationID  STRING QUERYABLE,
        photo           ASSET,
        photoOrder      INT64,
        taskID          STRING QUERYABLE,
        thumbnail       ASSET,
        uploadedAt      TIMESTAMP,
        uploadedBy      STRING QUERYABLE,
        GRANT READ, WRITE TO member,
        GRANT READ TO viewer
    );

    RECORD TYPE TeamMember (
        "___createTime" TIMESTAMP,
        "___createdBy"  REFERENCE,
        "___etag"       STRING,
        "___modTime"    TIMESTAMP,
        "___modifiedBy" REFERENCE,
        "___recordID"   REFERENCE,
        cloudKitUserID  STRING QUERYABLE,
        createdBy       STRING QUERYABLE,
        dateAdded       TIMESTAMP SORTABLE,
        email           STRING QUERYABLE SEARCHABLE SORTABLE,
        environment     STRING QUERYABLE,
        id              STRING QUERYABLE SEARCHABLE SORTABLE,
        isActive        INT64 QUERYABLE SORTABLE,
        jobTitle        STRING QUERYABLE SEARCHABLE SORTABLE,
        lastActive      TIMESTAMP SORTABLE,
        name            STRING QUERYABLE SEARCHABLE SORTABLE,
        organizationID  STRING QUERYABLE SEARCHABLE SORTABLE,
        permissions     LIST<STRING>,
        rates           BYTES QUERYABLE SORTABLE,
        role            STRING QUERYABLE SEARCHABLE SORTABLE,
        GRANT WRITE TO "_creator",
        GRANT CREATE TO "_icloud",
        GRANT READ TO "_world",
        GRANT READ, WRITE TO member
    );

    RECORD TYPE TestRecord (
        "___createTime" TIMESTAMP,
        "___createdBy"  REFERENCE,
        "___etag"       STRING,
        "___modTime"    TIMESTAMP,
        "___modifiedBy" REFERENCE,
        "___recordID"   REFERENCE,
        environment     STRING QUERYABLE,
        testField       STRING QUERYABLE SEARCHABLE SORTABLE,
        GRANT WRITE TO "_creator",
        GRANT CREATE TO "_icloud",
        GRANT READ TO "_world"
    );

    RECORD TYPE TimeEntry (
        "___createTime" TIMESTAMP,
        "___createdBy"  REFERENCE,
        "___etag"       STRING,
        "___modTime"    TIMESTAMP,
        "___modifiedBy" REFERENCE,
        "___recordID"   REFERENCE QUERYABLE,
        approvedAt      TIMESTAMP,
        approvedBy      STRING QUERYABLE,
        createdBy       STRING QUERYABLE,
        dateWorked      TIMESTAMP QUERYABLE SORTABLE,
        duration        DOUBLE QUERYABLE SORTABLE,
        endTime         TIMESTAMP QUERYABLE SORTABLE,
        environment     STRING QUERYABLE,
        hourlyRate      DOUBLE QUERYABLE,
        isApproved      INT64 QUERYABLE,
        isPaid          INT64 QUERYABLE,
        location        LOCATION,
        notes           STRING,
        organizationID  STRING QUERYABLE,
        projectID       STRING QUERYABLE,
        startTime       TIMESTAMP QUERYABLE SORTABLE,
        taskCategory    STRING QUERYABLE,
        taskDescription STRING,
        teamMemberID    STRING QUERYABLE,
        totalAmount     DOUBLE QUERYABLE SORTABLE,
        GRANT READ, WRITE TO member,
        GRANT READ TO viewer
    );

    RECORD TYPE Users (
        "___createTime" TIMESTAMP,
        "___createdBy"  REFERENCE QUERYABLE,
        "___etag"       STRING,
        "___modTime"    TIMESTAMP,
        "___modifiedBy" REFERENCE,
        "___recordID"   REFERENCE QUERYABLE,
        email           STRING,
        environment     STRING QUERYABLE,
        roles           LIST<INT64>,
        userID          STRING,
        GRANT READ, WRITE TO "_creator",
        GRANT READ TO "_icloud",
        GRANT READ, WRITE TO member
    );

    RECORD TYPE Vendor (
        "___createTime" TIMESTAMP,
        "___createdBy"  REFERENCE,
        "___etag"       STRING,
        "___modTime"    TIMESTAMP,
        "___modifiedBy" REFERENCE,
        "___recordID"   REFERENCE,
        address         STRING,
        category        STRING QUERYABLE SORTABLE,
        createdBy       STRING QUERYABLE,
        dateAdded       TIMESTAMP SORTABLE,
        email           STRING,
        environment     STRING QUERYABLE,
        id              STRING QUERYABLE SORTABLE,
        isActive        INT64 QUERYABLE,
        lastUpdated     TIMESTAMP SORTABLE,
        lastUsed        TIMESTAMP SORTABLE,
        name            STRING QUERYABLE SEARCHABLE SORTABLE,
        notes           STRING,
        organizationID  STRING QUERYABLE,
        phone           STRING,
        projectsUsed    LIST<STRING>,
        subcategories   LIST<STRING>,
        totalSpent      DOUBLE SORTABLE,
        GRANT READ, WRITE TO member,
        GRANT READ TO viewer
    );

    RECORD TYPE WorkHour (
        Creatableby     STRING,
        Readableby      STRING,
        WriteAccess     STRING,
        "___createTime" TIMESTAMP,
        "___createdBy"  REFERENCE,
        "___etag"       STRING,
        "___modTime"    TIMESTAMP,
        "___modifiedBy" REFERENCE,
        "___recordID"   REFERENCE QUERYABLE,
        approvedAt      TIMESTAMP,
        approvedBy      STRING QUERYABLE,
        createdBy       STRING QUERYABLE,
        date            TIMESTAMP QUERYABLE,
        description     STRING,
        employee        STRING QUERYABLE,
        environment     STRING QUERYABLE,
        hours           DOUBLE QUERYABLE,
        isPaid          INT64 QUERYABLE,
        lastSyncedAt    TIMESTAMP,
        organizationID  STRING QUERYABLE,
        projectID       STRING QUERYABLE,
        rate            DOUBLE QUERYABLE,
        taskType        STRING QUERYABLE,
        teamMemberID    STRING QUERYABLE,
        GRANT WRITE TO "_creator",
        GRANT CREATE TO "_icloud",
        GRANT READ TO "_world",
        GRANT READ, WRITE TO member
    );

    RECORD TYPE members (
        Example         STRING,
        FieldType       STRING,
        Purpose         STRING,
        "___createTime" TIMESTAMP,
        "___createdBy"  REFERENCE,
        "___etag"       STRING,
        "___modTime"    TIMESTAMP,
        "___modifiedBy" REFERENCE,
        "___recordID"   REFERENCE QUERYABLE,
        environment     STRING QUERYABLE,
        GRANT WRITE TO "_creator",
        GRANT READ, CREATE TO "_icloud",
        GRANT READ TO "_world"
    );

    RECORD TYPE pendingInvites (
        Example         STRING,
        FieldType       STRING,
        Purpose         STRING,
        "___createTime" TIMESTAMP,
        "___createdBy"  REFERENCE,
        "___etag"       STRING,
        "___modTime"    TIMESTAMP,
        "___modifiedBy" REFERENCE,
        "___recordID"   REFERENCE QUERYABLE,
        environment     STRING QUERYABLE,
        GRANT WRITE TO "_creator",
        GRANT READ, CREATE TO "_icloud",
        GRANT READ TO "_world"
    );